{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# **SWARM Data Processing Workflow**\n",
    "\n",
    "This document outlines the step-by-step process to extract, compute, and process SWARM magnetic field data using various scripts and repositories.\n",
    "\n",
    "## **Step 1: Identify AOI and Nearby Tracks**\n",
    "- **Script:** `plot_data_from_cdf_raw_data.ipynb`\n",
    "- **Objective:** Plot the Area of Interest (AOI) and find the closest dataset tracks for extraction.\n",
    "- **Output:** Identified dataset track to extract in `.txt` format.\n",
    "\n",
    "---\n",
    "\n",
    "## **Step 2: Extract Data from .CDF Files and Compute IGRF Model**\n",
    "- **Script:** `extract_data_from_cdf_to_txt.ipynb`\n",
    "- **Objective:** Extract data from `.cdf` files and compute **B_N, B_E, B_C** using the **IGRF Model**.\n",
    "- **Output:** A `.txt` file with the following header:\n",
    "  ```\n",
    "  Timestamp,Latitude,Longitude,Altitude,B_N_SWARM,B_E_SWARM,B_C_SWARM,B_N_IGRF,B_E_IGRF,B_C_IGRF (nT)\n",
    "  ```\n",
    "- **Modification:** Change the sign of **B_C_IGRF** to match the original dataset.\n",
    "\n",
    "---\n",
    "\n",
    "## **Step 3: Extract Coordinates and Prepare for Geomagnetic Calculation**\n",
    "- **Script:** `extract_coordinates_from_txt_file_to_use_in_geomag.ipynb`\n",
    "- **Objective:** Extract coordinates from the `.txt` file and prepare data for geomagnetic calculations.\n",
    "- **Task:** Extract every **100th point** from **HR files** for interpolation (since fetching the entire dataset via geomag is time-consuming). No need for LR dataset.\n",
    "\n",
    "---\n",
    "\n",
    "## **Step 4: Compute Geomagnetic Coordinates**\n",
    "- **Repository:** `geo2mag`\n",
    "- **Command:** Run the following command to compute geomagnetic coordinates:\n",
    "  ```sh\n",
    "  python GeomagConvert.py 2025 -f d:\\Data\\SWARM_data\\geomag\\geo2mag\\santorini_island\\coordinates_SW_OPER_MAGC_LR_1B_20250128T000000_20250128T235959_0606_MDR_MAG_LR.txt geomag\n",
    "  ```\n",
    "- **Output:** A `.txt` file with the following header:\n",
    "  ```\n",
    "  glat glon mlat mlon year\n",
    "  ```\n",
    "\n",
    "---\n",
    "\n",
    "## **Step 5: Interpolate Missing Data for HR Files**\n",
    "- **Script:** `interpolate_data.ipynb`\n",
    "- **Objective:** Interpolate missing geomagnetic data points for HR files.\n",
    "\n",
    "---\n",
    "\n",
    "## **Step 6: Insert mlat and mlon into the Existing Dataset**\n",
    "- **Script:** `insert_mlat_mlon_in_existing_txt_file.ipynb`\n",
    "- **Objective:** Insert **mlat** and **mlon** into the `.txt` file extracted from the original `.cdf` file.\n",
    "- **Columns Placement:** Insert as **Column 4 & 5** in the dataset.\n",
    "\n",
    "---\n",
    "\n",
    "## **Final Output**\n",
    "At the end of this workflow, you will have:\n",
    "- A **fully processed `.txt` file** containing the extracted, computed, and interpolated magnetic field data with geomagnetic coordinates.\n",
    "- Data ready for further analysis or visualization.\n",
    "\n",
    "---\n",
    "\n",
    "## **Additional Notes**\n",
    "- Ensure that all required Python dependencies and repositories (`geo2mag`, IGRF models, etc.) are installed and configured properly.\n",
    "- Always verify the consistency of `.txt` files before proceeding to the next step.\n",
    "- Use **HR data interpolation** to reduce processing time while maintaining accuracy.\n",
    "\n",
    "🚀 **Follow these steps carefully to ensure accurate data processing!**\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
